from django.db import models

class Squirrel(models.Model):
    x = models.FloatField()
    y = models.FloatField()
    unique_squirrel_id = models.CharField(max_length=1000)
    hectare = models.CharField(max_length=1000)
    shift = models.CharField(max_length=1000)
    date = models.DateField()
    hectare_squirrel_number = models.IntegerField()
    age = models.CharField(max_length=1000)
    primary_fur_color = models.CharField(max_length=1000)
    highlight_fur_color = models.CharField(max_length=1000)
    combination_of_primary_and_highlight_color = models.CharField(max_length=1000)
    color_notes = models.CharField(max_length=1000)
    location = models.CharField(max_length=1000)
    above_ground_sighter_measurement = models.CharField(max_length=1000)
    specific_location = models.CharField(max_length=1000)
    running = models.BooleanField()
    chasing = models.BooleanField()
    climbing = models.BooleanField()
    eating = models.BooleanField()
    foraging = models.BooleanField()
    other_activities = models.CharField(max_length=1000)
    kuks = models.BooleanField()
    quaas = models.BooleanField()
    moans = models.BooleanField()
    tail_flags = models.BooleanField()
    tail_twitches = models.BooleanField()
    approaches = models.BooleanField()
    indifferent = models.BooleanField()
    runs_from = models.BooleanField()
    other_interactions = models.CharField(max_length=1000)
    lat_long = models.CharField(max_length=1000)

# Create your models here.
