# Generated by Django 3.1.2 on 2020-10-22 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20201020_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='Latitude',
        ),
    ]
