# Generated by Django 3.1.2 on 2020-10-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_remove_squirrel_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='Latitude',
            field=models.FloatField(null=True),
        ),
    ]
